package Boletin26;

import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author otorradomiguez
 */
public class Boletin26 extends javax.swing.JFrame {

    private int contadorBotones = 0;
    private ArrayList<Integer> numerosJugados = new ArrayList();
    private ArrayList<Integer> numerosPremiados = new ArrayList();
    private int aciertos = 0;

    /**
     * Creates new form Boletin26
     */
    public Boletin26() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelNumeros.setLayout(new GridLayout(5, 10));
        for (int i = 1; i < 50; i++) {
            JButton botonNumero = new JButton("" + i);
            botonNumero.addMouseListener(new MouseAdapter() {
                /*Al crear el new mouseAdapter, escribimos los metodos que queremos
                usar entre corchetes tras el constructor*/
                @Override
                public void mouseClicked(MouseEvent e) {
                    JButton n = (JButton) e.getSource();

                    if (n.isEnabled()) {
                        if (contadorBotones < 6) {
                            contadorBotones++;
                            n.setEnabled(false);
                            numerosJugados.add(Integer.parseInt(n.getText()));
                        } else {
                            jLabelMensajes.setText("Solo puede seleccionar 6 numeros");
                        }
                    } else {
                        contadorBotones--;
                        n.setEnabled(true);
                        int indice = numerosJugados.indexOf(Integer.parseInt(n.getText()));
                        numerosJugados.remove(indice);
                    }
                    System.out.println(contadorBotones);
                    numerosJugados.sort(null);
                    System.out.println(numerosJugados.toString());
                }

            });
            panelNumeros.add(botonNumero);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNumeros = new javax.swing.JPanel();
        panelResultados = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jButtonJugar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jLabelRes = new javax.swing.JLabel();
        jLabelResultados = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jLabelNum = new javax.swing.JLabel();
        jLabelMisNumeros = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        Aciertos = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jLabelMensajes = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boletin 26 --Loteria--");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout panelNumerosLayout = new javax.swing.GroupLayout(panelNumeros);
        panelNumeros.setLayout(panelNumerosLayout);
        panelNumerosLayout.setHorizontalGroup(
            panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );
        panelNumerosLayout.setVerticalGroup(
            panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        getContentPane().add(panelNumeros, java.awt.BorderLayout.WEST);

        panelResultados.setLayout(new javax.swing.BoxLayout(panelResultados, javax.swing.BoxLayout.Y_AXIS));
        panelResultados.add(filler1);

        jButtonJugar.setText("Jugar");
        jButtonJugar.setAlignmentX(0.5F);
        jButtonJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonJugar.setMaximumSize(new java.awt.Dimension(100, 50));
        jButtonJugar.setPreferredSize(new java.awt.Dimension(100, 50));
        jButtonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJugarMouseClicked(evt);
            }
        });
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        panelResultados.add(jButtonJugar);
        panelResultados.add(filler2);

        jLabelRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRes.setText("Resultados");
        jLabelRes.setAlignmentX(0.5F);
        jLabelRes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelResultados.add(jLabelRes);

        jLabelResultados.setText("N/A");
        jLabelResultados.setAlignmentX(0.5F);
        jLabelResultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelResultados.add(jLabelResultados);
        panelResultados.add(filler3);

        jLabelNum.setText("Mis Numeros");
        jLabelNum.setAlignmentX(0.5F);
        jLabelNum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelResultados.add(jLabelNum);

        jLabelMisNumeros.setText("N/A");
        jLabelMisNumeros.setAlignmentX(0.5F);
        jLabelMisNumeros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelResultados.add(jLabelMisNumeros);
        panelResultados.add(filler4);

        Aciertos.setText("N/A");
        Aciertos.setAlignmentX(0.5F);
        Aciertos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelResultados.add(Aciertos);
        panelResultados.add(filler6);

        jLabelMensajes.setAlignmentX(0.5F);
        panelResultados.add(jLabelMensajes);

        getContentPane().add(panelResultados, java.awt.BorderLayout.CENTER);
        getContentPane().add(filler5, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJugarMouseClicked
        if (numerosJugados.size() == 6) {
            numerosPremiados.removeAll(numerosPremiados);
            aciertos=0;
            jLabelMensajes.setText("");
            Random rnd = new Random();
            for (int i = 0; i < 6; i++) {
                int num=rnd.nextInt(49)+1;
                if(numerosPremiados.contains(num)==false){
                numerosPremiados.add(num);
                }else{
                    i--;
                }
            }
            numerosPremiados.sort(null);
            jLabelMisNumeros.setText(numerosJugados.toString());
            jLabelResultados.setText(numerosPremiados.toString());
        } else {
            JOptionPane.showMessageDialog(this, "Debes elegir 6 numeros antes de jugar");       
        }
        for (int n : numerosPremiados) {
            if (numerosJugados.contains(n)) {
                aciertos++;
            }
        }
        Aciertos.setText("Has acertado " + aciertos + " numeros");
    }//GEN-LAST:event_jButtonJugarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boletin26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boletin26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boletin26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boletin26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boletin26().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aciertos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JLabel jLabelMensajes;
    private javax.swing.JLabel jLabelMisNumeros;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelRes;
    private javax.swing.JLabel jLabelResultados;
    private javax.swing.JPanel panelNumeros;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables

}
