package Boletin26;

import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author otorradomiguez
 */
public class Boletin26 extends javax.swing.JFrame {

    private int contadorBotones = 0;
    private ArrayList<Integer> numerosJugados = new ArrayList();
    private ArrayList<Integer> numerosPremiados = new ArrayList();
    private int aciertos=0;

    /**
     * Creates new form Boletin26
     */
    public Boletin26() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelNumeros.setLayout(new GridLayout(5, 10));
        for (int i = 1; i < 50; i++) {
            JButton botonNumero = new JButton("" + i);
            botonNumero.addMouseListener(new MouseAdapter() {
                /*Al crear el new mouseAdapter, escribimos los metodos que queremos
                usar entre corchetes tras el constructor*/
                @Override
                public void mouseClicked(MouseEvent e) {
                    JButton n = (JButton) e.getSource();

                    if (n.isEnabled()) {
                        if (contadorBotones < 6) {
                            contadorBotones++;
                            n.setEnabled(false);
                            numerosJugados.add(Integer.parseInt(n.getText()));                            
                        } else {
                            System.out.println("Solo puede seleccionar 6 numeros");
                        }
                    } else {
                        contadorBotones--;
                        n.setEnabled(true);
                        int indice=numerosJugados.indexOf(Integer.parseInt(n.getText()));
                        numerosJugados.remove(indice);
                    }
                    System.out.println(contadorBotones);
                    numerosJugados.sort(null);
                    System.out.println(numerosJugados.toString());
                }

            });
            panelNumeros.add(botonNumero);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNumeros = new javax.swing.JPanel();
        panelResultados = new javax.swing.JPanel();
        jButtonJugar = new javax.swing.JButton();
        jLabelRes = new javax.swing.JLabel();
        jLabelResultados = new javax.swing.JLabel();
        jLabelNum = new javax.swing.JLabel();
        jLabelMisNumeros = new javax.swing.JLabel();
        Aciertos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout panelNumerosLayout = new javax.swing.GroupLayout(panelNumeros);
        panelNumeros.setLayout(panelNumerosLayout);
        panelNumerosLayout.setHorizontalGroup(
            panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );
        panelNumerosLayout.setVerticalGroup(
            panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        getContentPane().add(panelNumeros, java.awt.BorderLayout.WEST);

        panelResultados.setLayout(new javax.swing.BoxLayout(panelResultados, javax.swing.BoxLayout.Y_AXIS));

        jButtonJugar.setText("Jugar");
        jButtonJugar.setAlignmentX(0.5F);
        jButtonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJugarMouseClicked(evt);
            }
        });
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        panelResultados.add(jButtonJugar);

        jLabelRes.setText("Resultados");
        jLabelRes.setAlignmentX(0.5F);
        panelResultados.add(jLabelRes);

        jLabelResultados.setText("N/A");
        jLabelResultados.setAlignmentX(0.5F);
        panelResultados.add(jLabelResultados);

        jLabelNum.setText("Mis Numeros");
        jLabelNum.setAlignmentX(0.5F);
        panelResultados.add(jLabelNum);

        jLabelMisNumeros.setText("N/A");
        jLabelMisNumeros.setAlignmentX(0.5F);
        panelResultados.add(jLabelMisNumeros);

        Aciertos.setText("N/A");
        Aciertos.setAlignmentX(0.5F);
        panelResultados.add(Aciertos);

        getContentPane().add(panelResultados, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJugarMouseClicked
        if(numerosJugados.size()==6){
        Random rnd = new Random();
        for (int i = 0; i < 6; i++) {
            numerosPremiados.add(rnd.nextInt(50));            
        }
        numerosPremiados.sort(null);
        System.out.println("Numeros Premiados: " + numerosPremiados.toString());
        }else{
            System.out.println("Debes elegir 6 numeros antes de jugar");
        }
        for(int n:numerosPremiados){
            if(numerosJugados.contains(n)){
                aciertos++;
            }            
        }
        System.out.println("Has acertado "+aciertos+" numeros.");
    }//GEN-LAST:event_jButtonJugarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boletin26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boletin26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boletin26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boletin26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boletin26().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aciertos;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JLabel jLabelMisNumeros;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelRes;
    private javax.swing.JLabel jLabelResultados;
    private javax.swing.JPanel panelNumeros;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables

}
